export const candidates = [
  {
    _id: "cand1",
    name: "Rohit Sharma",
    email: "rohit@gmail.com",
    password: "123456",
    googleId: null,
    githubId: null,
    location: "Mumbai, India",
  },
  {
    _id: "cand2",
    name: "Priya Patel",
    email: "priya@gmail.com",
    password: "123456",
    googleId: null,
    githubId: null,
    location: "Ahmedabad, India",
  },
  {
    _id: "cand3",
    name: "Arjun Mehta",
    email: "arjun@gmail.com",
    password: "123456",
    googleId: null,
    githubId: null,
    location: "Delhi, India",
  },
  {
    _id: "cand4",
    name: "Sneha Iyer",
    email: "sneha@gmail.com",
    password: "123456",
    googleId: null,
    githubId: null,
    location: "Bangalore, India",
  },
  {
    _id: "cand5",
    name: "Karan Singh",
    email: "karan@gmail.com",
    password: "123456",
    googleId: null,
    githubId: null,
    location: "Pune, India",
  },
];